export * from './Splash';
export * from './AdminLogin';
export * from './GeneralLogin';
export * from './Home';
export * from './Account';
export * from './Les';
export * from './Settings';
export * from './ListStudents';
export * from './EditStudent';
